# Generated by Django 4.2.30 on 2026-10-09 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_card_credit_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_code', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('device_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='device_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fraud_status',
            field=models.CharField(choices=[('NOT_CHECKED', 'Not Checked'), ('CLEAR', 'Clear'), ('FLAGGED', 'Flagged'), ('REVIEWED', 'Reviewed')], db_index=True, default='NOT_CHECKED', max_length=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='txn_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='txn_status_created_idx'),
        ),
        migrations.AddField(
            model_name='fraudlog',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_logs', to='payments.transaction'),
        ),
        migrations.AddField(
            model_name='fraudlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fraud_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='fraudlog',
            index=models.Index(fields=['rule_code', '-created_at'], name='fraud_rule_created_idx'),
        ),
    ]
